### ISSUE TITLE
preprocessed dataset available?

### ISSUE THREAD

**Issue by cristianmtr** [wayne391/Lead-Sheet-Analysis#4]
Hey

Any chance you have the entirety of the dataset available somewhere (GDrive or Dropbox)? Using it for a Deep Learning project in music generation

It's taking forever to download and process it

Cheers

**Comment by bearpelican** [comment]
This is the one I compiled from this project a month ago:
https://s3-us-west-2.amazonaws.com/ashaw-music/hooktheory_dataset.tar.gz

**Comment by cristianmtr** [comment]
The archive is no longer available. Could you please make it available again?

**Comment by wayne391** [comment]
Hello, my old dataset has some defects, which was corrected by @bearpelican. I recommend re-running the whole codes and I've opened the source XML [here](https://drive.google.com/file/u/1/d/13AEVD9xaZIaicEgd8tF1l6aOiRTymJxL/view?usp=sharing).
I'm working on some projects so I have no time to do it by myself.  But I think it can work properly.

**Comment by wayne391** [comment]
Hi.
Because the projects in our lab are finished, I'm allowed to make the whole dataset public. I've added the link in the README. You can check it out.

**Comment by rubencart** [comment]
@wayne391 Is the archive that you made public the "Hooktheory Lead Sheet Dataset (HLSD)" or the preprocessed "Hooktheory Pianoroll Triad Dataset (HTPD3)"? Since I would like the original chord symbols and not just the triads.

**Comment by andreamust** [comment]
@wayne391 @bearpelican Since the dataset is no longer available (as noted in Issue https://github.com/wayne391/lead-sheet-dataset/issues/6), would it be possible to share it again?

Thank you in advance for any help!
